name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:  
  build:
    runs-on: dotnet
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
         
              & D:\yaml\insert.ps1
        
            
        
