name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:  
  build:
    runs-on: dotnet
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
              & Stop-WebAppPool -Name "check"
              & 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe' -t:restore
              & 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe' demo_cicd.sln /p:DeployOnBuild=true /p:publishprofile=FolderProfile.pubxml
              & Start-WebAppPool -Name "check"  
              & D:\yaml\git.ps1
        
            
        
