name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:  
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: '12.x'
      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar'
      - name: Setup sonarqube
        uses: warchant/setup-sonar-scanner@v3
      - name: Run sonarqube
        run: sonar-scanner

    
      
      - name: Build
        run: |
         
              & 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe' -t:restore
              & 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe' demo_cicd.sln /p:DeployOnBuild=true /p:publishprofile=FolderProfile.pubxml
             
              & D:\yaml\git.ps1
        
